# Generated by Django 5.2.4 on 2025-07-31 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='id аккаунта')),
                ('balance', models.CharField(default=0, max_length=255, verbose_name='баланс')),
                ('balance_limit', models.CharField(default=0, max_length=255, verbose_name='ограничение баланса')),
                ('currency', models.CharField(max_length=255, verbose_name='валюта')),
                ('account_type', models.CharField(max_length=255, verbose_name='тип счета')),
            ],
            options={
                'verbose_name': 'счет водителя',
                'verbose_name_plural': 'счет водителя',
                'ordering': ['account_id'],
            },
        ),
        migrations.CreateModel(
            name='DriverWorkRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_rule_id', models.CharField(max_length=32, verbose_name='идентификатор условия работы')),
                ('is_enabled', models.BooleanField(verbose_name='доступно')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
            ],
            options={
                'verbose_name': 'условие работы',
                'verbose_name_plural': 'условия работы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Park',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('park_id', models.CharField(max_length=50, unique=True, verbose_name='id парка')),
                ('api_key', models.CharField(max_length=50, verbose_name='api ключ')),
                ('client_id', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='id клиента')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='название')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='город')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен')),
            ],
            options={
                'verbose_name': 'парк',
                'verbose_name_plural': 'парки',
                'ordering': ['city'],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_id', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='id водителя')),
                ('last_name', models.CharField(max_length=255, verbose_name='фамилия')),
                ('first_name', models.CharField(max_length=255, verbose_name='имя')),
                ('middle_name', models.CharField(blank=True, max_length=255, verbose_name='отчество')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Номер телефона')),
                ('driver_license_number', models.CharField(blank=True, max_length=255, verbose_name='номер ВУ')),
                ('driver_license_country', models.CharField(blank=True, max_length=255, verbose_name='страна ВУ')),
                ('driver_license_issue_date', models.CharField(blank=True, max_length=255, verbose_name='дата выдачи ВУ')),
                ('driver_license_expiration_date', models.CharField(blank=True, max_length=255, verbose_name='дата окончания ВУ')),
                ('work_status', models.CharField(blank=True, max_length=255, verbose_name='статус работы водителя')),
                ('created_date', models.CharField(blank=True, max_length=255, verbose_name='дата создания')),
                ('account', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='park.account', verbose_name='счет')),
                ('work_rule_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='park.driverworkrule', verbose_name='условия работы')),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_park', to='park.park', verbose_name='парк')),
            ],
            options={
                'verbose_name': 'водитель',
                'verbose_name_plural': 'водители',
                'ordering': ['last_name'],
            },
        ),
        migrations.AddField(
            model_name='driverworkrule',
            name='park',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='park.park', verbose_name='парк'),
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_id', models.CharField(max_length=32, unique=True, verbose_name='автомобиль')),
                ('brand', models.CharField(max_length=255, verbose_name='бренд')),
                ('model', models.CharField(max_length=255, verbose_name='модель')),
                ('year', models.PositiveSmallIntegerField(verbose_name='год')),
                ('vin', models.CharField(blank=True, max_length=255, verbose_name='vin')),
                ('color', models.CharField(max_length=255, verbose_name='цвет')),
                ('number', models.CharField(max_length=255, verbose_name='государственный номер')),
                ('callsign', models.CharField(max_length=255, verbose_name='позывной')),
                ('status', models.CharField(max_length=255, verbose_name='статус')),
                ('amenities', models.CharField(blank=True, max_length=255, verbose_name='удобства')),
                ('category', models.CharField(blank=True, max_length=255, verbose_name='категория ТС')),
                ('registration_cert', models.CharField(max_length=255, verbose_name='свидетельство о регистрации')),
                ('is_park_property', models.BooleanField(default=False, verbose_name='собственность парка')),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='park.park', verbose_name='парк')),
            ],
            options={
                'verbose_name': 'автомобиль',
                'verbose_name_plural': 'автомобили',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=255, unique=True, verbose_name='id заказа')),
                ('event_at', models.DateTimeField(verbose_name='завершен')),
                ('category', models.CharField(max_length=255, verbose_name='категория')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='название категории')),
                ('group_id', models.CharField(blank=True, default='', max_length=255, verbose_name='id группы')),
                ('group_name', models.CharField(blank=True, default='', max_length=255, verbose_name='название группы')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='стоимость')),
                ('description', models.CharField(max_length=255, verbose_name='описание')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_driver', to='park.driver', verbose_name='водитель')),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_park', to='park.park', verbose_name='парк')),
            ],
            options={
                'verbose_name': 'транзакция',
                'verbose_name_plural': 'транзакции',
                'ordering': ['-event_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=255, unique=True, verbose_name='id заказа')),
                ('created_at', models.DateTimeField(verbose_name='создан')),
                ('status', models.CharField(blank=True, default='', max_length=255, verbose_name='статус заказа')),
                ('payment_method', models.CharField(blank=True, default='', max_length=255, verbose_name='способ оплаты')),
                ('price', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='стоимость')),
                ('address_from', models.CharField(blank=True, default='', max_length=500, verbose_name='адрес откуда')),
                ('address_from_lat', models.CharField(blank=True, default='', max_length=50, verbose_name='адрес откуда широта')),
                ('address_from_lon', models.CharField(blank=True, default='', max_length=50, verbose_name='адрес откуда долгота')),
                ('address_to', models.CharField(blank=True, default='', max_length=500, verbose_name='адрес куда')),
                ('address_to_lat', models.CharField(blank=True, default='', max_length=50, verbose_name='адрес куда широта')),
                ('address_to_lon', models.CharField(blank=True, default='', max_length=50, verbose_name='адрес куда долгота')),
                ('cancellation_description', models.CharField(blank=True, default='', max_length=255, verbose_name='описание отмены')),
                ('car', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='park.car', verbose_name='автомобиль')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_driver', to='park.driver', verbose_name='водитель')),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_park', to='park.park', verbose_name='парк')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order_id'], name='park_order_order_i_bec9d3_idx')],
            },
        ),
        migrations.AlterUniqueTogether(
            name='driverworkrule',
            unique_together={('park', 'work_rule_id')},
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['driver_id'], name='park_driver_driver__331b7b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='driver',
            unique_together={('park', 'driver_id')},
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_id'], name='park_transa_transac_bd44cf_idx'),
        ),
    ]
