# Generated by Django 5.2.4 on 2025-07-31 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='phone',
        ),
    ]
