# Generated by Django 5.2.4 on 2025-07-31 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0002_remove_driver_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='work_rule_id',
            new_name='work_rule',
        ),
    ]
