# Generated by Django 5.2.4 on 2025-08-03 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0003_rename_work_rule_id_driver_work_rule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='driver_license_expiration_date',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='дата окончания ВУ'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='driver_license_issue_date',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='дата выдачи ВУ'),
        ),
    ]
