# Generated by Django 5.2.4 on 2025-08-03 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0004_alter_driver_driver_license_expiration_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='is_park_property',
        ),
        migrations.AlterField(
            model_name='car',
            name='amenities',
            field=models.CharField(blank=True, max_length=1500, verbose_name='удобства'),
        ),
        migrations.AlterField(
            model_name='car',
            name='category',
            field=models.CharField(blank=True, max_length=1500, verbose_name='категория ТС'),
        ),
    ]
