# Generated by Django 5.2.4 on 2025-08-04 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0005_remove_car_is_park_property_alter_car_amenities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='load_transaction_complete',
            field=models.BooleanField(default=False, verbose_name='загрузка транзакций завершена'),
        ),
    ]
