# Generated by Django 5.2.4 on 2025-08-04 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0006_order_load_transaction_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='order',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='transaction_order', to='park.order', verbose_name='заказ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='id заказа'),
        ),
    ]
