# Generated by Django 5.2.4 on 2025-08-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0007_transaction_order_alter_order_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='name',
            new_name='category_name',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='category',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='group_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='group_name',
        ),
        migrations.AddField(
            model_name='transaction',
            name='category_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='id категории'),
        ),
    ]
