# Generated by Django 5.2.4 on 2025-08-11 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0008_rename_name_transaction_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='category',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='категория'),
        ),
        migrations.AddField(
            model_name='order',
            name='mileage',
            field=models.CharField(blank=True, default=0, max_length=255, verbose_name='пробег'),
        ),
        migrations.AddField(
            model_name='order',
            name='short_id',
            field=models.CharField(default='', max_length=255, verbose_name='короткий id заказа'),
            preserve_default=False,
        ),
    ]
