# Generated by Django 5.2.4 on 2025-08-12 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0009_order_category_order_mileage_order_short_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='group_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='группа'),
        ),
    ]
