# Generated by Django 5.2.4 on 2025-08-12 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0010_transaction_group_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdersLoadState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_loaded_datetime', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
