# Generated by Django 5.2.4 on 2025-08-12 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0011_ordersloadstate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordersloadstate',
            options={'ordering': ['-updated_at'], 'verbose_name': 'статус загрузки заказов', 'verbose_name_plural': 'статусы загрузки заказов'},
        ),
    ]
