# Generated by Django 5.2.4 on 2025-08-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0012_alter_ordersloadstate_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateProcessing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_processed_date', models.DateField(verbose_name='Последняя обработанная дата')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Обработка дат',
                'verbose_name_plural': 'Обработка дат',
                'ordering': ['-last_processed_date'],
                'get_latest_by': 'last_processed_date',
            },
        ),
        migrations.DeleteModel(
            name='OrdersLoadState',
        ),
    ]
