# Generated by Django 5.2.4 on 2025-08-17 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0013_dateprocessing_delete_ordersloadstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='driver',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_driver', to='park.driver', verbose_name='водитель'),
        ),
    ]
