# Generated by Django 5.2.4 on 2025-08-19 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0014_alter_order_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(max_length=5000, verbose_name='описание'),
        ),
    ]
